# Generated by Django 4.1.2 on 2022-11-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='sond_id',
        ),
    ]
